### ISSUE TITLE
Scope and plan module

### ISSUE THREAD

**Issue by zerocrates** [omeka-s-modules/Collecting#1]

**Comment by jimsafley** [comment]
@sharonmleon @sheilabrennan

In the most general terms, here's this module's scope:

- Who's the audience?
  - anyone (open model)
  - registered contributors (restricted model)
- What will it accept?
  - contributor metadata
  - answers to prompts
  - files and file metadata
- Required features:
  - option to contribute anonymously
  - option to make contributions private

As I turn this scope into a plan, can anyone think of other _required_ features?

**Comment by jimsafley** [comment]
Ideas about a "Collecting" page block:

- "General Configuration"
    - [checkbox] "Require login/registration?"
    - [checkbox] "Enable file upload?"
    - [checkbox] "Enable multiple file upload?" (disable if file upload is disabled)
- "Contributor Questions"
    - [checkbox] "Name" (text; disable if login required)
    - [checkbox] "Email" (text; disable if login required)
    - [checkbox] "Location" (text)
    - [checkbox] "Contribute anonymously?" (checkbox)
    - [checkbox] "Make contribution private?" (checkbox)
    - 0-n custom questions (text, textarea, select, checkbox)
- "Contribution Metadata" (maps to item)
    - [checkbox] "Contribution Title" (text)
    - [checkbox] "Contribution Description" (textarea)
    - 0-n existing properties (text, textarea; using property selector)
- "File Metadata" (maps to the item's files; disable if file upload is disabled)
    - [checkbox] "File Title" (text)
    - [checkbox] "File Description" (textarea)
    - 0-n existing properties (text, textarea; using property selector)

**Comment by sheilabrennan** [comment]
@jimsafley I thought of something else: we need an option for admins to require that their contributors agree to a terms of service agreement (ie, some block text that is configured by the site admin) before submitting their contribution.

**Comment by jimsafley** [comment]
Thanks. I added it to "General Configuration" above.

**Comment by patrickmj** [comment]
The 'file upload' and file upload sound a little like they're thinking about the classic version. Should there be options for Media, and sources of media (allow YouTube, allow File upload, etc?) to reflect the move from File to Media in S?
