### ISSUE TITLE
How will we handle visibility of collected items?

### ISSUE THREAD

**Issue by jimsafley** [omeka-s-modules/Collecting#11]
Should collected items be made public or private by default? Either way, this module needs an interface to administer collected items, including updating their visibility. Note that only users with the "editor", "site admin", or "global admin" roles can update items that are created by other users. Site-specific roles are unrelated to Omeka resource management. 

@sheilabrennan

**Comment by sheilabrennan** [comment]
Private by default.

**Comment by sheilabrennan** [comment]
Can this review interface offer a preview of the contributed resource (ie, img thumb, snippet of text)?

**Comment by sheilabrennan** [comment]
Can the interface show item's status (public/not public/needs review)?

**Comment by jimsafley** [comment]
I'll work on an interface to quickly and efficiently administer the statuses of collected items. But before I do, **a)** what statuses do we need and **b)** what criteria needs to be met for each? We certainly need "private" and "public", but how would "needs review" work?

**Comment by sheilabrennan** [comment]
The use case for "needs review" is the status when something is first submitted and waiting for an admin to review it to make public or not. This might not be considered an actual status. But, as admin who has reviewed many contributions, it helps to have a visual flag to tell me that an item is new and needs my attention. Is there a way to handle that, which makes sense to you w/in the module?
