### ISSUE TITLE
User questions need an anonymous option 

### ISSUE THREAD

**Issue by sheilabrennan** [omeka-s-modules/Collecting#15]
As a user, I want the option to contribute anonymously when asked to give my name. 
Anonymous would appear on the public item as the creator/contributor.

**Comment by jimsafley** [comment]
I'm closing in on a solution that's flexible and simple to understand. How about we make a distinction between **a)** user inputs that are never shown publicly, and **b)** user inputs that are shown publicly but only under certain conditions. "User Private" prompts are like the ones we currently have, where the labels and user input are never accessible to the public. "User Public" prompts will have special treatment defined by a form-wide "Anonymity" setting. I see three options for this setting:

* **User sets own anonymity**: when this is set, the form will include a "Submit this item anonymously" checkbox. If checked, all "User Public" inputs will be treated as anonymous.
* **All "User Public" inputs are anonymous**: when this is set, the form will not include the checkbox and all "User Public" inputs will be treated as anonymous.
* **No "User Public" inputs are anonymous**: when this is set, the form will not include the checkbox and all "User Public" inputs will be displayed.

This setting can be changed midstream depending on the needs of the institution. It's up to the form builder to determine which prompts are appropriate to be treated as "User Public". With the new "Separator" prompt, form builders can describe to the user which inputs are treated as public/anonymous.

**Comment by sheilabrennan** [comment]
I like this very much. What you've described provided both the admins/project managers and the end users ability to collect/ share on their terms.  Thank you!

**Comment by patrickmj** [comment]
This sounds nicely to address the issues of Contribution for Classic that have built up over the years.
Is there a mechanism for aligning multiple contributions from the same anonymous person?

**Comment by jimsafley** [comment]
> Is there a mechanism for aligning multiple contributions from the same anonymous person?

Anonymity is separate from identity. If the user is logged in (we'll deal with a "Guest User" module later) all items submitted by that user can be aligned. If the user is not logged in, we create a collecting user without an associated Omeka user. Those users cannot be aligned.

**Comment by patrickmj** [comment]
Makes sense. I wish we had more real data about how much researchers care about lining up multiple contributions from the same person. Our Marathon seemed to not care much, but as a research principle it seems relevant. How much we decide to care will probably guide whether we want/need a Guest User module.
