### ISSUE TITLE
Review interface for collected items

### ISSUE THREAD

**Issue by jimsafley** [omeka-s-modules/Collecting#17]
We need an interface to quickly and efficiently review and administer collected items. A reviewer should be able to paginate through an orderable list of collected items and view a snapshot of each item without leaving the page. A reviewer should be able to quickly toggle the status of the collected items. The statuses are as follows:

* **Needs Review**: this item has not been reviewed
* **Public**: this item has been reviewed and made public
* **Private**: this item has been reviewed and made private

@sheilabrennan Is there need for any other statuses, or do we want to keep it simple?

As in #13, I'm probably going to need @kimisgold's help here, particularly the "view a snapshot of each item without leaving the page" part.

**Comment by sheilabrennan** [comment]
Keep it simple. This works for me.
