### ISSUE TITLE
Required fields need an indicator on the form

### ISSUE THREAD

**Issue by mebrett** [omeka-s-modules/Collecting#19]
The public view of the form doesn't have an indication of which fields are required

(Title and Which Park are required)

<img width="814" alt="screen shot 2016-08-25 at 12 09 22 pm" src="https://cloud.githubusercontent.com/assets/2314070/17976823/1753c16e-6abd-11e6-8af4-a7bc53439032.png">

**Comment by jimsafley** [comment]
@kimisgold I'll need your help figuring out the best way to style public forms. Right now they use the same markup and styles as the admin interface, but there are some differences in styles that we have to account for.
