### ISSUE TITLE
What will the "Collecting" block look like to the public?

### ISSUE THREAD

**Issue by jimsafley** [omeka-s-modules/Collecting#2]
@sheilabrennan 

I'm currently working out how the "Collecting" page block will look to the public. On the admin side, when a user adds a "Collecting" block, the block form asks which collecting forms should be available within that block. (Note that forms are site-specific and that one-or-more forms can be assigned to one page block.)

What I'm wondering is how the public page will look. Should the forms be rendered in full within the page? Or should there be links to the forms on a separate, standalone page? Any other ideas on how to present the "Collecting" page block to the end user?

**Comment by jimsafley** [comment]
It's important to note that even if a form is rendered and submitted within the block, we must handle the form within another action, meaning the user will be taken away from the page, at least temporarily. Also, due to the way we render pages, if a user submits an invalid form, we'll need to render the form in a separate view anyway.

**Comment by sheilabrennan** [comment]
Good question!
I think the forms should be rendered in full on the page, and your caveat about the way pages work make sense in this context.  

@sharonmleon any opinions on this?
