### ISSUE TITLE
Email submissions to users

### ISSUE THREAD

**Issue by jimsafley** [omeka-s-modules/Collecting#23]
Once submitted, there needs to be an option to email users their submission.

**Comment by sheilabrennan** [comment]
I always love options. Can we give users the opt-in?

I think the current email text we have is pretty good. Let me see if I can find it in the current plugin.

**Comment by sheilabrennan** [comment]
Does this work?

Thank you for contributing. 

Your contribution will appear in the site once an administrator approves it, if you have given us  permission to publish.

Feel free to make another contribution or to browse the website.

**Comment by jimsafley** [comment]
Fixed in 065420ba9ff59e3a6d7d6e41b16aa62663983704
