### ISSUE TITLE
More testing

### ISSUE THREAD

**Issue by jimsafley** [omeka-s-modules/Collecting#24]
I made some changes that require you to pull from master and reinstall the module. Of note is the new "Success Text" HTML editor and the new "User Name" and "User Email" prompt types in the form builder.

The "Success Text" editor allows you to customize the public form's post-submission page. The two new prompt types are special types that can occur in a form only once. Should the form builder decide to use them, they provide unambiguous info about the user that's used in the citation and, eventually, in the post-submission email.

I'd like you to test these features out specifically, and create new issues for any questions, bug reports, and UI/UX issues as you continue to explore the module.

@sheilabrennan @mebrett

**Comment by jimsafley** [comment]
I added the email feature, so you'll need to pull from master and reinstall the module again. Now, if the form includes an "User Email" prompt, we ask the user if we should "Email me my submission". Test this feature out and the resulting email.

**Comment by mebrett** [comment]
The "email me a copy of my submission doesn't result in an email being sent. Instead, the when the user clicks submit, they get a page with the email text: http://dev.omeka.org/omeka-s/s/usnps/collecting/2/submit displaying 
Date: Fri, 09 Sep 2016 19:15:25

>  +0000 From: outreach@omeka.org To: megan.brett+test@gmail.com Subject: Thank you for your submission MIME-Version: 1.0 Content-Type: multipart/mixed; boundary="=_4e57cfc005ae72cd748141f2a9464570" This is a message in Mime Format. If you see this, your mail reader does not support this format. --=_4e57cfc005ae72cd748141f2a9464570 Content-Type: text/html Content-Transfer-Encoding: 8bit Thank you for sharing your park photo with the Omeka S test site National Parks. We will review your submission and, if appropriate, publish it to the site. --=_4e57cfc005ae72cd748141f2a9464570 Content-Type: text/plain Content-Transfer-Encoding: 8bit You submitted the following data on September 9, 2016 using the form “Your Park Photo” on the site “National Parks”: http://dev.omeka.org/omeka-s/s/usnps # Title Photo # What does this photo show? Description # What park is this picture from? Olympic --=_4e57cfc005ae72cd748141f2a9464570--
