### ISSUE TITLE
Testing: "Item Resource" input type

### ISSUE THREAD

**Issue by jimsafley** [omeka-s-modules/Collecting#32]
The [item-input-type](https://github.com/omeka-s-modules/Collecting/tree/item-input-type) branch introduces the "Item Resource" input type to the "Item Property" prompt type. Put simply, it allows Collecting form users to select an item resource as the input of a property, much like we can do in the admin interface (see #31).

When a form builder add/edits a prompt and selects the "Item Property" prompt type, they'll see the new "Item Resource" input type. Selecting that opens the "Filter Query" field where they can enter an advanced search query to filter the items available to the Collecting form user. On the public form, the resulting prompt should have a select menu containing all filtered items in the format `#{itemId}: {itemTitle}`. Once entered and submitted, the collected item should have the selected item resource assigned to it.

**Comment by mebrett** [comment]
Some initial thoughts from testing:
On review, the collected inputs only give the item id, not title - might be more useful to include abbreviated/shortened title.

On the form itself, the list shows item id first and then item title. On the one hand, I'm not sure how aware contributor-visitors are of item IDs, but on the other I can see it being useful for sites with multiple items with the same title (names, for instance, often repeat down generations).

**Comment by jimsafley** [comment]
The collected inputs only give the item ID, but the item should translate that into a resource value. Are they not?

Yes, I feel the ID is necessary to disambiguate items with the same title.

**Comment by mebrett** [comment]
It gets translated into a resource value on the item's metadata tab, but not in the Collecting tab or the summary info on the site's collected item review. So if you're reviewing submissions and you want to know what's linked, it's 2-3 clicks to get that info. 
<img width="834" alt="screen shot 2017-05-30 at 1 15 42 pm" src="https://cloud.githubusercontent.com/assets/2314070/26599015/14dacd66-4545-11e7-8b2c-c6c6d7d1bfec.png">

<img width="840" alt="screen shot 2017-05-30 at 1 15 59 pm" src="https://cloud.githubusercontent.com/assets/2314070/26599029/2565d432-4545-11e7-9bf5-616bced953b6.png">

**Comment by mebrett** [comment]
One note that will need to be addressed in the themes is that long titles cause the drop down menu to become huge - extending out of the browser window and sometimes taking up the width of the screen. This was true for all four themes, although with Center Row the dropdown menus themselves extended off the screen. (there are some Very Long Titles in my test install).

![screen shot 2017-05-30 at 2 49 13 pm](https://cloud.githubusercontent.com/assets/2314070/26599812/eb81a37e-4547-11e7-91fb-f377271652e1.png)

**Comment by jimsafley** [comment]
Items are now linked in the review sidebar. Does this work for you?

**Comment by jimsafley** [comment]
Item titles are now truncated at 80 characters. Does this work for you?

**Comment by mebrett** [comment]
Item title display in the review sidebar is a huge improvement. Thank you.

Dropdown no longer extends outside the browser window, although its appearance in Cozy theme is still a bit odd (it's extending just past the defined area and so looks cut off), but the functionality is significantly improved. 

Data on the item's admin-side view, on the Collecting tab, is now a little funky. No longer displaying just the id (yay!) but giving raw html. 
<img width="712" alt="screen shot 2017-05-31 at 1 22 26 pm" src="https://cloud.githubusercontent.com/assets/2314070/26644917/5e4a4228-4604-11e7-949d-5185cd0ab0b9.png">

**Comment by jimsafley** [comment]
I pushed a fix that should render the item link in the collecting tab.

**Comment by mebrett** [comment]
Item links are now rendered as proper, clickable links. Everything works, as far as I can tell.
