### ISSUE TITLE
Collecting forms not visible to Editors

### ISSUE THREAD

**Issue by patrickmj** [omeka-s-modules/Collecting#35]
On the admin side for a site as an Editor, I see the link to the Collecting forms page, but forms do not show up. There's also no button to add a new form.

I'm not sure what the intended permissions through all the roles and options should be.

**Comment by jimsafley** [comment]
Yes, currently only site admins can create and delete collecting forms. I remember my logic as being "if a user can't delete a form they shouldn't be able to create one." My assumption is that form creation and deletion is not an editorial purview, but an administrative one. Editors can update forms and add forms to site pages.

**Comment by patrickmj** [comment]
Thanks. Weirdly, yesterday the form created wasn't showing up for editors, but today it is (some kind of caching thing?). Editor cannot update the form, though.

**Comment by jimsafley** [comment]
I just updated an existing form as a site editor. Were you talking about global roles? I'm talking about site roles.

**Comment by patrickmj** [comment]
Ah, yes. Sorry. Was talking about global role of editor. That user isn't added to the site. So is the idea  that global editor can look through everything, but needs to be added to the site to be able to edit?

**Comment by patrickmj** [comment]
Part of my confusion was that the site was created by that user with global editor role, but being the owner didn't give all those permissions. So, this might be a core issue.

**Comment by jimsafley** [comment]
Yes, perhaps users that create sites should automatically be added as the site admin, regardless their global role.
