### ISSUE TITLE
Allow file upload collectors attach number of files.

### ISSUE THREAD

**Issue by buckett** [omeka-s-modules/Collecting#36]
Currently when you add an upload media in your collection form it only allows the end user to attach one file. In some cases user may be attaching varying numbers of files. While you can add multiple upload media items to your collection form catering for the edge case of 20 when most items need just one or 2 uploads leads to a cluttered form.

Would it be possible to either add a new Media Type of Upload (multiple) that allows multiple files uploads or allow the existing Upload to be configured to allow multiple files?

**Comment by jimsafley** [comment]
Thanks for the request. It's seems like a good idea but may be tricky to implement. We'll look into it.

**Comment by jimsafley** [comment]
The [multiple-file](/omeka-s-modules/Collecting/tree/multiple-file) branch adds a "Upload Multiple" media type that uses the file input's ["multiple" attribute](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input#attr-multiple). Users may select multiple files in the browser's native file picker using Ctrl/Shift+click. This is in addition to the existing single-select "Upload" media type.

I'm going to merge it into master depending on further consideration, testing, and feedback.

**Comment by patrickmj** [comment]
I think that it might be better left as a next release after our wholesale release on Tuesday.

**Comment by buckett** [comment]
Thanks for this, we're running the multiple-file branch locally and will let you know if we encounter any problems, in initial testing it's working a treat.

**Comment by buckett** [comment]
Might this get merged into master?

**Comment by jimsafley** [comment]
Merged in 2d50da08d1f315a7ecce5fba12862431002f6d3e
