### ISSUE TITLE
Testing: CustomVocab integration

### ISSUE THREAD

**Issue by jimsafley** [omeka-s-modules/Collecting#39]
The [custom-vocab branch](https://github.com/omeka-s-modules/Collecting/tree/custom-vocab) adds integration with the CustomVocab module for the following prompt types: item property, item supplementary, user private, user public. After selecting one of these you should be able to select a "Custom vocab" input type and then select from the list of custom vocabularies that were created via CustomVocab. Remember to add the changes and save the form. When viewing the form on a public site you should be able to select from the custom vocabulary and successfully submit the form. The resulting item should show that the selected vocab string was saved.

**Comment by mebrett** [comment]
Tested successfully on chrome (on windows and mac), firefox, and safari.
