### ISSUE TITLE
CAPTCHA?

### ISSUE THREAD

**Issue by jimsafley** [omeka-s-modules/Collecting#4]
@sheilabrennan I assume we want to add CAPTCHA protection to the collecting forms. Should it be an always-on feature, or should form builders be able to toggle it on/off? Do we still like reCAPTCHA?

**Comment by sheilabrennan** [comment]
Yes, we want that option for form builders, to turn on/off.

Good question about whether we still like reCaptcha.  Do you like some of the alternatives better these days?

**Comment by jimsafley** [comment]
See #5
