### ISSUE TITLE
Edit collecting form alignment issues

### ISSUE THREAD

**Issue by mebrett** [omeka-s-modules/Collecting#40]
On `master` and `custom vocab` branches, there's something off about the way the elements of the form are shown: 
<img width="981" alt="screen shot 2019-01-28 at 2 39 46 pm" src="https://user-images.githubusercontent.com/2314070/51861709-e202f300-230a-11e9-8439-df681f3bae1e.png">

**Comment by jimsafley** [comment]
Fixed in 49d9d3a79e19bd82a37248163431b334745978ef
