### ISSUE TITLE
Testing: Numeric input types

### ISSUE THREAD

**Issue by jimsafley** [omeka-s-modules/Collecting#43]
The [numeric-input-types branch](https://github.com/omeka-s-modules/Collecting/tree/numeric-input-types) introduces the following input types: "Numeric timestamp," "Numeric interval," "Numeric duration," and "Numeric integer." These should be available when the [NumericDataTypes module](https://github.com/omeka-s-modules/NumericDataTypes) is active and the version >= 1.2.0 (when it introduced numeric form elements).

When editing a Collecting form add a prompt. The new input types should be available after selecting the "Item Property," "Item Supplementary," "User Private," or "User Public" prompt types. Test each new input type on public collecting form. They should look and behave identically to those provided by the NumericDataTypes module. After submitting the form, check that the data is correctly saved to the item.

**Comment by mebrett** [comment]
All of the data comes in as expected.

The data displays in what I suppose is raw(er) format on the collecting tab for the item, which is where you go from the Collecting module section for the site when reviewing collected items. These results aren't always easy to parse - if it's difficult to change what you see on this tab, we can just document the fact that's the raw numeric data as stored and direct people to click over to the Metadata tab for the item

Ex (see "How long" field)
<img width="699" alt="screen shot 2019-02-21 at 1 14 32 pm" src="https://user-images.githubusercontent.com/2314070/53191885-06d14a00-35db-11e9-97b9-bab382601143.png">

**Comment by jimsafley** [comment]
The connection between the stored data and how it's rendered is tenuous once it's duplicated into the collecting_input table. It's best just to document this as you describe.
