### ISSUE TITLE
Multiline prompts break table-like layout in form editor

### ISSUE THREAD

**Issue by lmullen** [omeka-s-modules/Collecting#58]
Here is an example of a form where the prompts end up getting out of line with the item properties.

<img width="822" alt="image" src="https://user-images.githubusercontent.com/183672/79478537-88ebb180-7fd9-11ea-96a5-13723f27fcae.png">

**Comment by kimisgold** [comment]
There were some flexbox shenanigans on that first column that was throwing height off. Pulling the latest from master should fix it.
