### ISSUE TITLE
User prompts

### ISSUE THREAD

**Issue by jimsafley** [omeka-s-modules/Collecting#6]
Right now forms have prompts that describe the collected item, but they don't have any that describe the user. Collecting forms should have separate "Item Prompts" and "User Prompts" sections, the latter of which should have "Property" and "Supplementary" prompts and include an option to render a map for user-geolocation. Like "Item Prompts" user prompts will be sortable, customizable, and can be toggled optional/required.

(Note that I'm avoiding any use of the words "contributor" or "contribution" since those are exclusive of other purposes for collecting things.)

One question for @sheilabrennan: should the "User Prompts" be set by the form builder or by the site administrator?

**Comment by jimsafley** [comment]
After discussion we came to the conclusion that user prompts will be set by the form builder. Any administrative restrictions on them can be added later if needed. Also, I'm considering not implementing the "Property" type for user prompts. A form user doesn't correspond to an Omeka S resource, so the advantages of including it are minimal.

**Comment by sheilabrennan** [comment]
Ok, that works for me.
