### ISSUE TITLE
Testing: Email address 

### ISSUE THREAD

**Issue by jimsafley** [omeka-s-modules/Collecting#60]
In the master branch I've added a feature that allows site administrators to specify an email from which submission emails are sent. You should find a new "Email address" input on the site settings page under the "Collecting" section. There are now two behaviors, depending on whether a Collecting email address is set:

- No email set (default): Submission emails should be **from** the global administrator's address. 
- Email is set: Submission emails should be **from** the address set in site settings.

(Test this on core's master branch.)

**Comment by mebrett** [comment]
If I checked "send me a copy of my submission," I saw the emails as coming from the right account as per your notes.
