### ISSUE TITLE
private fields only viewable to site admins

### ISSUE THREAD

**Issue by GitByrd** [omeka-s-modules/Collecting#62]
Hi, we have a couple of reviewers on our Omeka site whose only role is to approve items that come through the collecting form. They need to be able to see the private fields in order to approve or disapprove items.  I noticed that the only way for them to see these fields is to upgrade their user account to "site admin" - and wouldn't you know it, as soon as I did that, they accidentally deleted an item! This is why they are reviewers. 

Could you please make it an option for reviewers to see private fields? 

Thanks!

**Comment by jimsafley** [comment]
Thanks for finding this bug. Reviewers (and editors) should be able to view all collected data, including private input text, user name, and user email. I've made a branch that fixes this. We'll make a release after we test it.
