### ISSUE TITLE
Testing: more restrictive viewing of private collected data

### ISSUE THREAD

**Issue by jimsafley** [omeka-s-modules/Collecting#64]
[This release](https://github.com/omeka-s-modules/Collecting/releases/tag/v1.5.1) made it so any Omeka S reviewer or editor can view private collected data, but, after consideration, I find this to be far too permissive.

The latest commits to the master branch are an attempt to patch this issue. Now, only reviewers or editors _who are also editors of the site_ can view private collected data. I find this precaution to be a good faith effort to keep private data private while retaining a review workflow for users who are not global or site administrators.

To test this: a reviewer or editor who is either a) not a member of the site, or b) a site "viewer" should not be able to see "User Private," "User Name," and "User Email" text; a reviewer or editor who is a site "editor" or "admin" should be able to see them.

**Comment by mebrett** [comment]
Reviewer user cannot see any of the metadata for the collected story in Collecting form view unless added to the site as an *editor* (even viewer doesn't work).
If an item has been made public, the item's content continues to show up as Private in the collecting form view, although it can be seen on the metadata view once clicked through to the item:

**Reviewer as Viewer**
<img width="806" alt="Screen Shot 2020-06-17 at 10 28 31 AM" src="https://user-images.githubusercontent.com/2314070/84910793-51ef5600-b085-11ea-9759-a0f236f8af61.png">
<img width="802" alt="Screen Shot 2020-06-17 at 10 28 28 AM" src="https://user-images.githubusercontent.com/2314070/84910794-51ef5600-b085-11ea-81ec-6a1c29a575d9.png">

**Comment by jimsafley** [comment]
I've made a change that should allow reviewers+ to see all user input data.
