### ISSUE TITLE
Testing: Notification email

### ISSUE THREAD

**Issue by jimsafley** [omeka-s-modules/Collecting#70]
Test on `master` branch. I've introduced a feature that lets administrators send a notification email after users submit items.  In site settings, under the "Collecting" section, enter your email into "Notification email address". Then go to a public form and submit something. You should receive an email containing submission data and a link to the review page. Note that your installation must have email configured and working for this to work.

**Comment by sharonmleon** [comment]
The email worked fine, but the link to the item in the site was not a properly formed URL:
`http:///workspace/omeka-s/admin/site/s/mall/collecting/1/item`

Should be: 
http://6floors.org/workspace/omeka-s/admin/item/6587

**Comment by zerocrates** [comment]
_probably_ just an issue of not using an absolute URL in the email.

**Comment by sharonmleon** [comment]
Sorry, I was wrong about this, the URL should be http://6floors.org/workspace/omeka-s/admin/site/s/mall/collecting/1/item 

That suggests that John is right and that I didn't actually pay attention to where the email was sending me: to the review panel, and not to the items browse.

**Comment by zerocrates** [comment]
But the "it didn't have your domain name in the link" part is still the same, yes?

**Comment by sharonmleon** [comment]
Yes. I was just wrong about what the link should have been. It was the correct relative destination, but it definitely needed the absolute link.

**Comment by sharonmleon** [comment]
Fixed, and functional.
