### ISSUE TITLE
'Page not found' on submission if URL doesn't contain '/s/omeka'

### ISSUE THREAD

**Issue by lguariento** [omeka-s-modules/Collecting#76]
Hello,

I'm getting this error after clicking 'submit' on a form:

```
Page not found

The page you are trying to view does not exist. Use the back button to return to the last page.

Page not found.

Reason: error-controller-not-found
```

The page address is `...collecting/1/submit`. I am using the [Clean URL module](https://gitlab.com/Daniel-KM/Omeka-S-module-CleanUrl) configured so that I the `s/site-slug` is skipped. Deactivating the module (i.e. using the default `s/site-slug` bit) solves the issue. Is it possible to customise the controller for the success page in these cases?

Omeka S 3.2.1

**Comment by jimsafley** [comment]
Similar to #46, this is not a bug in the Collecting module. You may want to create an issue in the Clean URL module.

**Comment by lguariento** [comment]
[Thank you](https://gitlab.com/Daniel-KM/Omeka-S-module-CleanUrl/-/issues/19).
