### ISSUE TITLE
User authentication

### ISSUE THREAD

**Issue by lguariento** [omeka-s-modules/Collecting#77]
Is it possible to use this module with a more robust authentication system? For instance for crowdsourcing projects, checking that the email exists and gathering genuine information about the user?

**Comment by lguariento** [comment]
I'm looking into the [Guest module](https://gitlab.com/Daniel-KM/Omeka-S-module-Guest/), when I manage to install it I hope I'll be able to do what I need.

**Comment by jimsafley** [comment]
One solution is to create Omeka S user accounts for the users and track them that way. If a user is logged in while using Collecting, any contributed item is owned by that user.

**Comment by lguariento** [comment]
Great, and yes, the Guest module should be able to help me achieve that.

Is there a way of telling Collecting to only work/show if a (guest) user is logged-in?

**Comment by jimsafley** [comment]
No, but you could not add the collecting form to navigation and give users with accounts a direct link.

**Comment by lguariento** [comment]
Excellent. I'll play around with it tomorrow and will confirm it's doing what I want to achieve.

**Comment by jimsafley** [comment]
It may be possible if you modify the theme directly. But this is beyond the scope of this module.

**Comment by lguariento** [comment]
Thank you. But is it at least posible to add an option 'prevent not-logged-in users to submit form' to this module?

**Comment by jimsafley** [comment]
There is already an issue (#74) to that effect. We'll look into it.
