### ISSUE TITLE
Multiple "Deprecated: trim():" errors after creating a form within a site 

### ISSUE THREAD

**Issue by CSSSchaffer** [omeka-s-modules/Collecting#87]
I installed version 1.11.0 on our Omeka 4.0.3 instance (after completely uninstalling and deleting our old version of Collecting module, and making sure the old tables in the database were dropped - so to ensure a fresh install) and the following errors occurred when I created a new collecting form inside one of our Omeka S websites: 

Deprecated: trim(): Passing null to parameter #1 ($string) of type string is deprecated in /home/schaffer/dev.schafferlibrarycollections.org/modules/Collecting/src/Entity/CollectingPrompt.php on line 170

Deprecated: trim(): Passing null to parameter #1 ($string) of type string is deprecated in /home/schaffer/dev.schafferlibrarycollections.org/modules/Collecting/src/Entity/CollectingPrompt.php on line 190

Deprecated: trim(): Passing null to parameter #1 ($string) of type string is deprecated in /home/schaffer/dev.schafferlibrarycollections.org/modules/Collecting/src/Entity/CollectingPrompt.php on line 200

Deprecated: trim(): Passing null to parameter #1 ($string) of type string is deprecated in /home/schaffer/dev.schafferlibrarycollections.org/modules/Collecting/src/Entity/CollectingPrompt.php on line 222

Deprecated: trim(): Passing null to parameter #1 ($string) of type string is deprecated in /home/schaffer/dev.schafferlibrarycollections.org/modules/Collecting/src/Entity/CollectingPrompt.php on line 190

Deprecated: trim(): Passing null to parameter #1 ($string) of type string is deprecated in /home/schaffer/dev.schafferlibrarycollections.org/modules/Collecting/src/Entity/CollectingPrompt.php on line 200

Deprecated: trim(): Passing null to parameter #1 ($string) of type string is deprecated in /home/schaffer/dev.schafferlibrarycollections.org/modules/Collecting/src/Entity/CollectingPrompt.php on line 222

Deprecated: trim(): Passing null to parameter #1 ($string) of type string is deprecated in /home/schaffer/dev.schafferlibrarycollections.org/modules/Collecting/src/Entity/CollectingPrompt.php on line 180

Deprecated: trim(): Passing null to parameter #1 ($string) of type string is deprecated in /home/schaffer/dev.schafferlibrarycollections.org/modules/Collecting/src/Entity/CollectingPrompt.php on line 190

Deprecated: trim(): Passing null to parameter #1 ($string) of type string is deprecated in /home/schaffer/dev.schafferlibrarycollections.org/modules/Collecting/src/Entity/CollectingPrompt.php on line 200

Deprecated: trim(): Passing null to parameter #1 ($string) of type string is deprecated in /home/schaffer/dev.schafferlibrarycollections.org/modules/Collecting/src/Entity/CollectingPrompt.php on line 222

**Comment by jimsafley** [comment]
Thanks for finding and reporting this error. Since PHP 8.1, passing `null` to built-in string functions raises a deprecation message. The fix will be in the next release, which should be published soon.

**Comment by CSSSchaffer** [comment]
Ahh, I see. Thanks for the update!
